#!/bin/sh
# Author:     {{ full_name|default('TODO: CHANGEME', true) }} <{{ email|default('TODO: CHANGEME', true) }}>
# Contact:    {{ contact_name|default("TODO: CHANGEME", true) }} <{{ contact_email|default('TODO: CHANGEME', true) }}>
# Project:    {{ project_name|default("TODO: CHANGEME", true) }}
# Proj Home:  {{ project_home|default("TODO: CHANGEME", true) }}
# Copyright:  {{ software_copyright|default("TODO: CHANGEME", true) }}
# License:    {{ software_license|default("TODO: CHANGEME", true) }}
# Revised:    {{ date|default("TODO: CHANGEME", true) }} # This revision is for the test-suite portion
# Created:    {{ date|default("TODO: CHANGEME", true) }}
##--==
#==============================================================================
{{ script_name|default("TODO: CHANGEME", true) }}() {
    #:"""
    #: .. function:: {{ script_name|default("TODO: CHANGEME", true) }}()
    #:
    #: .. project:: {{ project_name|default("TODO: CHANGEME", true) }} <{{ project_home|default("TODO: CHANGEME", true) }}>
    #:
    #: .. revision:: {{ date|default("TODO: CHANGEME", true) }}
    #:
    #: {{ script_synopsis|default("TODO: CHANGEME", true) }}
    #:"""

    return
}
##==---
#==============================================================================
if ! (return 0 2>/dev/null) ; then
    {{ script_name|default("TODO: CHANGEME", true) }} "${@}"
fi
